package main

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func generateFile(gen *protogen.Plugin, f *protogen.File) error {
	if len(f.Messages) == 0 && len(f.Enums) == 0 {
		return nil
	}

	base := strings.TrimSuffix(f.Desc.Path(), ".proto") + "_bitpacker"
	base = filepath.ToSlash(base)

	hFile := gen.NewGeneratedFile(base+".h", "")
	cFile := gen.NewGeneratedFile(base+".c", "")

	if err := writeHeader(hFile, f); err != nil {
		return err
	}
	if err := writeSource(cFile, f, base+".h"); err != nil {
		return err
	}
	return nil
}

func headerGuard(base string) string {
	s := strings.ToUpper(base)
	s = strings.NewReplacer("/", "_", ".", "_", "-", "_").Replace(s)
	return s + "_H"
}

// writeHeader generates the .h file: includes, enums, structs, function declarations.
func writeHeader(g *protogen.GeneratedFile, f *protogen.File) error {
	guard := headerGuard(strings.TrimSuffix(f.Desc.Path(), ".proto") + "_bitpacker")
	p := g.P

	p("/* ", filepath.Base(f.Desc.Path()), " — generated by protoc-gen-bitpacker-c, do not edit */")
	p("#ifndef ", guard)
	p("#define ", guard)
	p()
	p("#include <stdint.h>")
	p("#include <stdbool.h>")
	p("#include <string.h>")
	p("#include \"bitpacker_runtime.h\"")
	for _, h := range importedHeaders(f) {
		p("#include \"", h, "\"")
	}
	p()

	if len(f.Enums) > 0 {
		p("/* ── Enums ───────────────────────────────────────────────────────────── */")
		p()
		for _, e := range f.Enums {
			writeEnumTypedef(g, e)
		}
	}

	if len(f.Messages) > 0 {
		p("/* ── Forward declarations ────────────────────────────────────────────── */")
		p()
		for _, msg := range f.Messages {
			emitForwardDecls(g, msg)
		}
		p()
	}

	// Oneof discriminant enums (must come before struct definitions)
	for _, msg := range f.Messages {
		if err := emitOneofEnums(g, msg); err != nil {
			return err
		}
	}

	if len(f.Messages) > 0 {
		p("/* ── Structs ─────────────────────────────────────────────────────────── */")
		p()
		visited := map[protoreflect.FullName]bool{}
		for _, msg := range f.Messages {
			if err := writeStructsInOrder(g, msg, visited); err != nil {
				return err
			}
		}
	}

	if len(f.Messages) > 0 {
		p("/* ── Public API (returns bytes consumed/written, or -1 on error) ──────── */")
		p()
		for _, msg := range f.Messages {
			emitFuncDecls(g, msg, false)
		}
		p()
		p("/* ── Internal API (shared bit cursor; called by generated code of importing files) ── */")
		p()
		for _, msg := range f.Messages {
			emitFuncDecls(g, msg, true)
		}
		p()
	}

	p("#endif /* ", guard, " */")
	return nil
}

// importedHeaders returns the headers of other proto files whose enums or messages are
// stored by the generated structs of f, sorted for stable output. Types that occupy no
// storage (Timestamp, empty messages) and map fields (unsupported) need no include.
func importedHeaders(f *protogen.File) []string {
	seen := map[string]bool{}
	var walk func(msgs []*protogen.Message)
	walk = func(msgs []*protogen.Message) {
		for _, msg := range msgs {
			walk(msg.Messages)
			if units, _ := collectUnits(msg); units == nil {
				continue
			}
			for _, field := range msg.Fields {
				fd := field.Desc
				var dep protoreflect.FileDescriptor
				switch {
				case fd.IsMap():
					continue
				case fd.Kind() == protoreflect.EnumKind:
					dep = fd.Enum().ParentFile()
				case fd.Kind() == protoreflect.MessageKind && !isTimestampMsg(fd.Message()) && !isEmptyMsg(fd.Message()):
					dep = fd.Message().ParentFile()
				default:
					continue
				}
				if dep.Path() != f.Desc.Path() {
					seen[headerPath(dep)] = true
				}
			}
		}
	}
	walk(f.Messages)

	headers := make([]string, 0, len(seen))
	for h := range seen {
		headers = append(headers, h)
	}
	sort.Strings(headers)
	return headers
}

func emitForwardDecls(g *protogen.GeneratedFile, msg *protogen.Message) {
	if msg.Desc.IsMapEntry() {
		return
	}
	units, _ := collectUnits(msg)
	if units != nil && msgHasNonMapFields(msg) {
		g.P("typedef struct ", cMsgTypeName(msg.Desc), " ", cMsgTypeName(msg.Desc), ";")
	}
	for _, nested := range msg.Messages {
		emitForwardDecls(g, nested)
	}
}

func emitOneofEnums(g *protogen.GeneratedFile, msg *protogen.Message) error {
	if msg.Desc.IsMapEntry() {
		return nil
	}
	msgName := string(msg.Desc.Name())
	for _, oneof := range msg.Oneofs {
		if oneof.Desc.IsSynthetic() {
			continue
		}
		typeName := cOneofWhichTypeName(msgName, string(oneof.Desc.Name()))
		noneName := cOneofNoneEnumerant(msgName, string(oneof.Desc.Name()))
		g.P("typedef enum {")
		g.P("    ", noneName, " = 0,")
		for i, field := range oneof.Fields {
			name := cOneofEnumerantName(msgName, string(oneof.Desc.Name()), string(field.Desc.Name()))
			g.P("    ", name, " = ", i+1, ",")
		}
		g.P("} ", typeName, ";")
		g.P()
	}
	for _, nested := range msg.Messages {
		if err := emitOneofEnums(g, nested); err != nil {
			return err
		}
	}
	return nil
}

func writeEnumTypedef(g *protogen.GeneratedFile, e *protogen.Enum) {
	typeName := cEnumTypeName(e.Desc)
	g.P("typedef enum {")
	for _, v := range e.Values {
		g.P("    ", e.Desc.Name(), "_", v.Desc.Name(), " = ", int32(v.Desc.Number()), ",")
	}
	g.P("} ", typeName, ";")
	g.P()
}

func writeStructsInOrder(g *protogen.GeneratedFile, msg *protogen.Message, visited map[protoreflect.FullName]bool) error {
	if msg.Desc.IsMapEntry() || visited[msg.Desc.FullName()] {
		return nil
	}
	visited[msg.Desc.FullName()] = true
	for _, nested := range msg.Messages {
		if err := writeStructsInOrder(g, nested, visited); err != nil {
			return err
		}
	}
	// Message fields are stored by value, so same-file field types must be complete first.
	for _, field := range msg.Fields {
		if field.Message == nil || field.Desc.IsMap() || field.Message.Desc.ParentFile() != msg.Desc.ParentFile() {
			continue
		}
		if err := writeStructsInOrder(g, field.Message, visited); err != nil {
			return err
		}
	}
	return writeStructDef(g, msg)
}

func writeStructDef(g *protogen.GeneratedFile, msg *protogen.Message) error {
	// Only generate structs for messages with valid bitpacker annotations
	units, err := collectUnits(msg)
	if err != nil {
		return err
	}
	if units == nil {
		return nil
	}

	// Check if we'd produce at least one non-comment struct field.
	// A message where ALL fields are maps (unsupported) would have an empty struct.
	hasFields := false
	for _, field := range msg.Fields {
		fd := field.Desc
		if fd.ContainingOneof() != nil && !fd.ContainingOneof().IsSynthetic() {
			continue // handled in union
		}
		if !fd.IsMap() {
			hasFields = true
			break
		}
	}
	if !hasFields && len(msg.Oneofs) == 0 {
		// All fields are maps — skip this message
		return nil
	}

	name := cMsgTypeName(msg.Desc)
	g.P("struct ", name, " {")
	for _, field := range msg.Fields {
		fd := field.Desc
		if od := fd.ContainingOneof(); od != nil && !od.IsSynthetic() {
			continue // handled in oneof union below
		}
		if err := writeStructField(g, field); err != nil {
			return err
		}
	}
	// Oneof unions
	for _, oneof := range msg.Oneofs {
		if oneof.Desc.IsSynthetic() {
			continue
		}
		if err := writeOneofUnion(g, oneof, msg); err != nil {
			return err
		}
	}
	g.P("};")
	g.P()
	return nil
}

func writeStructField(g *protogen.GeneratedFile, field *protogen.Field) error {
	fd := field.Desc
	fo := bpFieldOpts(fd)
	name := string(fd.Name())

	// Skip map fields (not supported in MVP)
	if fd.IsMap() {
		g.P("    /* map field '", name, "' not supported — skipped */")
		return nil
	}

	if fd.IsList() {
		return writeRepeatedField(g, fd, fo, name)
	}

	switch {
	case fd.Kind() == protoreflect.MessageKind && isTimestampMsg(fd.Message()):
		g.P("    bool        has_", name, ";")
		g.P("    int64_t     ", name, ";")
	case fd.Kind() == protoreflect.MessageKind:
		g.P("    bool        has_", name, ";")
		if !isEmptyMsg(fd.Message()) {
			g.P("    ", cMsgTypeName(fd.Message()), " ", name, ";")
		}
	case fd.ContainingOneof() != nil && fd.ContainingOneof().IsSynthetic():
		// proto3 optional scalar
		g.P("    bool        has_", name, ";")
		if err := writeScalarField(g, fd, fo, name); err != nil {
			return err
		}
	default:
		if err := writeScalarField(g, fd, fo, name); err != nil {
			return err
		}
	}
	return nil
}

func writeScalarField(g *protogen.GeneratedFile, fd protoreflect.FieldDescriptor, fo bpOpts, name string) error {
	switch fd.Kind() {
	case protoreflect.StringKind:
		max := maxArraySize(fo.lengthBits)
		g.P("    char        ", name, "[", max+1, "];")
		g.P("    uint16_t    ", name, "_len;")
	case protoreflect.BytesKind:
		max := maxArraySize(fo.lengthBits)
		g.P("    uint8_t     ", name, "[", max, "];")
		g.P("    uint16_t    ", name, "_len;")
	case protoreflect.EnumKind:
		g.P("    ", cEnumTypeName(fd.Enum()), " ", name, ";")
	default:
		g.P("    ", cScalarType(fd.Kind()), " ", name, ";")
	}
	return nil
}

func writeRepeatedField(g *protogen.GeneratedFile, fd protoreflect.FieldDescriptor, fo bpOpts, name string) error {
	max := maxArraySize(fo.countBits)

	switch fd.Kind() {
	case protoreflect.MessageKind:
		switch {
		case isTimestampMsg(fd.Message()):
			g.P("    int64_t     ", name, "[", max, "];")
		case !isEmptyMsg(fd.Message()):
			g.P("    ", cMsgTypeName(fd.Message()), " ", name, "[", max, "];")
		}
	case protoreflect.StringKind:
		strMax := maxArraySize(fo.lengthBits)
		g.P("    char        ", name, "[", max, "][", strMax+1, "];")
		g.P("    uint16_t    ", name, "_lens[", max, "];")
	case protoreflect.BytesKind:
		bytesMax := maxArraySize(fo.lengthBits)
		g.P("    uint8_t     ", name, "[", max, "][", bytesMax, "];")
		g.P("    uint16_t    ", name, "_lens[", max, "];")
	case protoreflect.EnumKind:
		g.P("    ", cEnumTypeName(fd.Enum()), " ", name, "[", max, "];")
	default:
		g.P("    ", cScalarType(fd.Kind()), " ", name, "[", max, "];")
	}
	g.P("    uint16_t    ", name, "_count;")
	return nil
}

func writeOneofUnion(g *protogen.GeneratedFile, oneof *protogen.Oneof, msg *protogen.Message) error {
	msgName := string(msg.Desc.Name())
	oneofName := string(oneof.Desc.Name())
	typeName := cOneofWhichTypeName(msgName, oneofName)

	var members []string
	for _, field := range oneof.Fields {
		fd := field.Desc
		fo := bpFieldOpts(fd)
		name := string(fd.Name())
		switch fd.Kind() {
		case protoreflect.MessageKind:
			switch {
			case isTimestampMsg(fd.Message()):
				members = append(members, fmt.Sprint("int64_t     ", name, ";"))
			case !isEmptyMsg(fd.Message()):
				members = append(members, fmt.Sprint(cMsgTypeName(fd.Message()), " ", name, ";"))
			}
		case protoreflect.StringKind:
			max := maxArraySize(fo.lengthBits)
			members = append(members, fmt.Sprint("struct { char data[", max+1, "]; uint16_t len; } ", name, ";"))
		case protoreflect.BytesKind:
			max := maxArraySize(fo.lengthBits)
			members = append(members, fmt.Sprint("struct { uint8_t data[", max, "]; uint16_t len; } ", name, ";"))
		case protoreflect.EnumKind:
			members = append(members, fmt.Sprint(cEnumTypeName(fd.Enum()), " ", name, ";"))
		default:
			members = append(members, fmt.Sprint(cScalarType(fd.Kind()), " ", name, ";"))
		}
	}

	g.P("    ", typeName, " which_", oneofName, ";")
	// C99 forbids empty unions; a oneof of only empty messages is just its tag.
	if len(members) == 0 {
		return nil
	}
	g.P("    union {")
	for _, m := range members {
		g.P("        ", m)
	}
	g.P("    } ", oneofName, ";")
	return nil
}

// emitFuncDecls declares the public buffer API, or with internal set, the _r/_w functions
// that take a shared bit cursor so nested messages can be packed without byte alignment.
func emitFuncDecls(g *protogen.GeneratedFile, msg *protogen.Message, internal bool) {
	if msg.Desc.IsMapEntry() {
		return
	}
	units, _ := collectUnits(msg)
	if units != nil && msgHasNonMapFields(msg) {
		name := cMsgTypeName(msg.Desc)
		if internal {
			g.P("int bp_encode_", name, "_w(const ", name, " *msg, bp_writer_t *w);")
			g.P("int bp_decode_", name, "_r(", name, " *msg, bp_reader_t *r);")
		} else {
			g.P("int bp_encode_", name, "(const ", name, " *msg, uint8_t *buf, uint32_t buf_size);")
			g.P("int bp_decode_", name, "(", name, " *msg, const uint8_t *buf, uint32_t buf_len);")
		}
	}
	for _, nested := range msg.Messages {
		emitFuncDecls(g, nested, internal)
	}
}

// ── Source file ───────────────────────────────────────────────────────────────

func writeSource(g *protogen.GeneratedFile, f *protogen.File, hInclude string) error {
	g.P("/* ", filepath.Base(f.Desc.Path()), " — generated by protoc-gen-bitpacker-c, do not edit */")
	g.P("#include \"", filepath.Base(hInclude), "\"")
	g.P()

	// Collect all messages that have valid bitpacker units
	var msgs []*protogen.Message
	collectBitpackerMsgs(f.Messages, &msgs)

	// Internal _r/_w functions are declared in the header, so definition order is free.
	for _, msg := range msgs {
		if err := writeMsgFunctions(g, msg); err != nil {
			return err
		}
	}
	return nil
}

// collectBitpackerMsgs gathers messages (in dependency order) that have valid bitpacker units
// AND at least one non-map field (to avoid generating empty structs/functions).
func collectBitpackerMsgs(msgs []*protogen.Message, out *[]*protogen.Message) {
	for _, msg := range msgs {
		if msg.Desc.IsMapEntry() {
			continue
		}
		collectBitpackerMsgs(msg.Messages, out) // nested first
		units, _ := collectUnits(msg)
		if units != nil && msgHasNonMapFields(msg) {
			*out = append(*out, msg)
		}
	}
}

// msgHasNonMapFields returns true if the message has at least one encodable non-map field.
func msgHasNonMapFields(msg *protogen.Message) bool {
	for _, field := range msg.Fields {
		if !field.Desc.IsMap() {
			return true
		}
	}
	return len(msg.Oneofs) > 0
}

func writeMsgFunctions(g *protogen.GeneratedFile, msg *protogen.Message) error {
	units, err := collectUnits(msg)
	if err != nil || units == nil {
		return err
	}

	name := cMsgTypeName(msg.Desc)

	// Internal decode function (takes bp_reader_t*)
	g.P("int bp_decode_", name, "_r(", name, " *msg, bp_reader_t *r) {")
	g.P("    uint64_t _v;")
	for _, u := range units {
		if err := emitDecodeUnit(g, u, msg, "r"); err != nil {
			return err
		}
	}
	g.P("    return 0;")
	g.P("}")
	g.P()

	// Public decode wrapper
	g.P("int bp_decode_", name, "(", name, " *msg, const uint8_t *buf, uint32_t buf_len) {")
	g.P("    bp_reader_t r = {buf, 0, buf_len * 8u};")
	g.P("    if (bp_decode_", name, "_r(msg, &r) != 0) return -1;")
	g.P("    return (int)((r.bit_pos + 7u) / 8u);")
	g.P("}")
	g.P()

	// Internal encode function (takes bp_writer_t*)
	g.P("int bp_encode_", name, "_w(const ", name, " *msg, bp_writer_t *w) {")
	g.P("    uint64_t _v; (void)_v;")
	for _, u := range units {
		if err := emitEncodeUnit(g, u, msg, "w"); err != nil {
			return err
		}
	}
	g.P("    return 0;")
	g.P("}")
	g.P()

	// Public encode wrapper
	g.P("int bp_encode_", name, "(const ", name, " *msg, uint8_t *buf, uint32_t buf_size) {")
	g.P("    bp_writer_t w = {buf, 0, buf_size * 8u};")
	g.P("    if (bp_encode_", name, "_w(msg, &w) != 0) return -1;")
	g.P("    return (int)bp_writer_finish(&w);")
	g.P("}")
	g.P()

	return nil
}

// ── Decode ────────────────────────────────────────────────────────────────────

func emitDecodeUnit(g *protogen.GeneratedFile, u unit, msg *protogen.Message, rv string) error {
	switch u := u.(type) {
	case scalarUnit:
		return emitDecodeScalar(g, u, msg, rv)
	case oneofUnit:
		return emitDecodeOneof(g, u, msg, rv)
	}
	return nil
}

func emitDecodeScalar(g *protogen.GeneratedFile, u scalarUnit, msg *protogen.Message, rv string) error {
	fd := u.fd
	fo := u.fo
	name := string(fd.Name())

	// Skip map fields
	if fd.IsMap() {
		g.P("    /* map field '", name, "' skipped */")
		return nil
	}

	if u.isOptional {
		g.P("    /* optional ", name, " */")
		g.P("    if (bp_read_bits(", rv, ", 1, &_v)) return -1;")
		g.P("    msg->has_", name, " = (bool)_v;")
		g.P("    if (msg->has_", name, ") {")
		if err := emitDecodeScalarValue(g, fd, fo, "msg->"+name, "        ", rv); err != nil {
			return err
		}
		g.P("    }")
		return nil
	}

	if u.isTimestamp {
		bits := fo.bits
		if bits == 0 {
			bits = 64
		}
		g.P("    /* timestamp ", name, " */")
		g.P("    if (bp_read_bits(", rv, ", 1, &_v)) return -1;")
		g.P("    msg->has_", name, " = (bool)_v;")
		g.P("    if (msg->has_", name, ") {")
		g.P("        if (bp_read_bits(", rv, ", ", bits, ", &_v)) return -1;")
		g.P("        msg->", name, " = (int64_t)_v;")
		g.P("    }")
		return nil
	}

	if u.isMessage {
		nestedName := cMsgTypeName(fd.Message())
		g.P("    /* message ", name, " */")
		g.P("    if (bp_read_bits(", rv, ", 1, &_v)) return -1;")
		g.P("    msg->has_", name, " = (bool)_v;")
		if !isEmptyMsg(fd.Message()) {
			g.P("    if (msg->has_", name, ") {")
			g.P("        if (bp_decode_", nestedName, "_r(&msg->", name, ", ", rv, ") != 0) return -1;")
			g.P("    }")
		}
		return nil
	}

	if fd.IsList() {
		return emitDecodeList(g, fd, fo, name, rv)
	}

	return emitDecodeScalarValue(g, fd, fo, "msg->"+name, "    ", rv)
}

func emitDecodeList(g *protogen.GeneratedFile, fd protoreflect.FieldDescriptor, fo bpOpts, name, rv string) error {
	g.P("    /* repeated ", name, " */")
	g.P("    if (bp_read_bits(", rv, ", ", fo.countBits, ", &_v)) return -1;")
	g.P("    msg->", name, "_count = (uint16_t)_v;")
	g.P("    for (uint16_t _i = 0; _i < msg->", name, "_count; _i++) {")

	switch fd.Kind() {
	case protoreflect.MessageKind:
		if !isEmptyMsg(fd.Message()) {
			nestedName := cMsgTypeName(fd.Message())
			g.P("        if (bp_decode_", nestedName, "_r(&msg->", name, "[_i], ", rv, ") != 0) return -1;")
		}
	case protoreflect.StringKind:
		max := maxArraySize(fo.lengthBits)
		g.P("        if (bp_read_bits(", rv, ", ", fo.lengthBits, ", &_v)) return -1;")
		g.P("        if (_v > ", max, "u) return -1;")
		g.P("        msg->", name, "_lens[_i] = (uint16_t)_v;")
		g.P("        if (bp_read_raw_bytes(", rv, ", msg->", name, "_lens[_i], (uint8_t*)msg->", name, "[_i])) return -1;")
		g.P("        msg->", name, "[_i][msg->", name, "_lens[_i]] = '\\0';")
	case protoreflect.BytesKind:
		max := maxArraySize(fo.lengthBits)
		g.P("        if (bp_read_bits(", rv, ", ", fo.lengthBits, ", &_v)) return -1;")
		g.P("        if (_v > ", max, "u) return -1;")
		g.P("        msg->", name, "_lens[_i] = (uint16_t)_v;")
		g.P("        if (bp_read_raw_bytes(", rv, ", msg->", name, "_lens[_i], msg->", name, "[_i])) return -1;")
	default:
		if err := emitDecodeScalarValue(g, fd, fo, fmt.Sprintf("msg->%s[_i]", name), "        ", rv); err != nil {
			return err
		}
	}

	g.P("    }")
	return nil
}

func emitDecodeScalarValue(g *protogen.GeneratedFile, fd protoreflect.FieldDescriptor, fo bpOpts, dest, indent, rv string) error {
	switch fd.Kind() {
	case protoreflect.BoolKind:
		g.P(indent, "if (bp_read_bits(", rv, ", 1, &_v)) return -1;")
		g.P(indent, dest, " = (bool)_v;")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P(indent, "if (bp_read_bits(", rv, ", ", fo.bits, ", &_v)) return -1;")
		g.P(indent, dest, " = (uint32_t)_v;")
	case protoreflect.Int32Kind, protoreflect.Sfixed32Kind:
		g.P(indent, "if (bp_read_bits(", rv, ", ", fo.bits, ", &_v)) return -1;")
		g.P(indent, dest, " = bp_sign_ext32(_v, ", fo.bits, ");")
	case protoreflect.Sint32Kind:
		g.P(indent, "if (bp_read_bits(", rv, ", ", fo.bits, ", &_v)) return -1;")
		g.P(indent, dest, " = bp_zagzig32((uint32_t)_v);")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P(indent, "if (bp_read_bits(", rv, ", ", fo.bits, ", &_v)) return -1;")
		g.P(indent, dest, " = _v;")
	case protoreflect.Int64Kind, protoreflect.Sfixed64Kind:
		g.P(indent, "if (bp_read_bits(", rv, ", ", fo.bits, ", &_v)) return -1;")
		g.P(indent, dest, " = bp_sign_ext64(_v, ", fo.bits, ");")
	case protoreflect.Sint64Kind:
		g.P(indent, "if (bp_read_bits(", rv, ", ", fo.bits, ", &_v)) return -1;")
		g.P(indent, dest, " = bp_zagzig64(_v);")
	case protoreflect.FloatKind:
		return emitDecodeFloat(g, fo, dest, indent, rv)
	case protoreflect.DoubleKind:
		return emitDecodeDouble(g, fo, dest, indent, rv)
	case protoreflect.StringKind:
		max := maxArraySize(fo.lengthBits)
		lenDest := dest + "_len"
		g.P(indent, "if (bp_read_bits(", rv, ", ", fo.lengthBits, ", &_v)) return -1;")
		g.P(indent, "if (_v > ", max, "u) return -1;")
		g.P(indent, lenDest, " = (uint16_t)_v;")
		g.P(indent, "if (bp_read_raw_bytes(", rv, ", ", lenDest, ", (uint8_t*)", dest, ")) return -1;")
		g.P(indent, dest, "[", lenDest, "] = '\\0';")
	case protoreflect.BytesKind:
		max := maxArraySize(fo.lengthBits)
		lenDest := dest + "_len"
		g.P(indent, "if (bp_read_bits(", rv, ", ", fo.lengthBits, ", &_v)) return -1;")
		g.P(indent, "if (_v > ", max, "u) return -1;")
		g.P(indent, lenDest, " = (uint16_t)_v;")
		g.P(indent, "if (bp_read_raw_bytes(", rv, ", ", lenDest, ", ", dest, ")) return -1;")
	case protoreflect.EnumKind:
		g.P(indent, "if (bp_read_bits(", rv, ", ", fo.bits, ", &_v)) return -1;")
		g.P(indent, dest, " = (", cEnumTypeName(fd.Enum()), ")_v;")
	}
	return nil
}

func emitDecodeFloat(g *protogen.GeneratedFile, fo bpOpts, dest, indent, rv string) error {
	if fo.isFixed {
		g.P(indent, "if (bp_read_bits(", rv, ", ", fo.bits, ", &_v)) return -1;")
		if fo.isSigned {
			g.P(indent, dest, " = bp_fixed_to_float(bp_sign_ext64(_v, ", fo.bits, "), ", fo.decimalPlaces, ");")
		} else {
			g.P(indent, dest, " = bp_ufixed_to_float(_v, ", fo.decimalPlaces, ");")
		}
		return nil
	}
	bits := fo.bits
	if bits == 0 {
		bits = 32
	}
	switch bits {
	case 16:
		g.P(indent, "if (bp_read_bits(", rv, ", 16, &_v)) return -1;")
		g.P(indent, dest, " = bp_f16_to_f32((uint16_t)_v);")
	default:
		g.P(indent, "if (bp_read_bits(", rv, ", 32, &_v)) return -1;")
		g.P(indent, "{ uint32_t _b32 = (uint32_t)_v; memcpy(&", dest, ", &_b32, 4); }")
	}
	return nil
}

func emitDecodeDouble(g *protogen.GeneratedFile, fo bpOpts, dest, indent, rv string) error {
	if fo.isFixed {
		g.P(indent, "if (bp_read_bits(", rv, ", ", fo.bits, ", &_v)) return -1;")
		if fo.isSigned {
			g.P(indent, dest, " = bp_fixed_to_double(bp_sign_ext64(_v, ", fo.bits, "), ", fo.decimalPlaces, ");")
		} else {
			g.P(indent, dest, " = bp_ufixed_to_double(_v, ", fo.decimalPlaces, ");")
		}
		return nil
	}
	bits := fo.bits
	if bits == 0 {
		bits = 64
	}
	switch bits {
	case 16:
		g.P(indent, "if (bp_read_bits(", rv, ", 16, &_v)) return -1;")
		g.P(indent, dest, " = (double)bp_f16_to_f32((uint16_t)_v);")
	case 32:
		g.P(indent, "if (bp_read_bits(", rv, ", 32, &_v)) return -1;")
		g.P(indent, "{ uint32_t _b32 = (uint32_t)_v; float _f; memcpy(&_f, &_b32, 4); ", dest, " = (double)_f; }")
	default:
		g.P(indent, "if (bp_read_bits(", rv, ", 64, &_v)) return -1;")
		g.P(indent, "memcpy(&", dest, ", &_v, 8);")
	}
	return nil
}

func emitDecodeOneof(g *protogen.GeneratedFile, u oneofUnit, msg *protogen.Message, rv string) error {
	msgName := string(msg.Desc.Name())
	oneofName := string(u.od.Name())
	noneName := cOneofNoneEnumerant(msgName, oneofName)

	g.P("    /* oneof ", oneofName, " */")
	g.P("    if (bp_read_bits(", rv, ", ", u.selectorBits, ", &_v)) return -1;")
	g.P("    msg->which_", oneofName, " = (", cOneofWhichTypeName(msgName, oneofName), ")_v;")
	g.P("    switch (msg->which_", oneofName, ") {")
	g.P("    case ", noneName, ": break;")

	for i, field := range u.fields {
		fd := field.fd
		fo := field.fo
		fname := string(fd.Name())
		enumerant := cOneofEnumerantName(msgName, oneofName, fname)
		g.P("    case ", enumerant, ": /* selector=", i+1, " */")
		switch fd.Kind() {
		case protoreflect.MessageKind:
			if !isEmptyMsg(fd.Message()) {
				nestedName := cMsgTypeName(fd.Message())
				g.P("        if (bp_decode_", nestedName, "_r(&msg->", oneofName, ".", fname, ", ", rv, ") != 0) return -1;")
			}
		case protoreflect.StringKind:
			g.P("        if (bp_read_bits(", rv, ", ", fo.lengthBits, ", &_v)) return -1;")
			g.P("        msg->", oneofName, ".", fname, ".len = (uint16_t)_v;")
			g.P("        if (bp_read_raw_bytes(", rv, ", msg->", oneofName, ".", fname, ".len, (uint8_t*)msg->", oneofName, ".", fname, ".data)) return -1;")
			g.P("        msg->", oneofName, ".", fname, ".data[msg->", oneofName, ".", fname, ".len] = '\\0';")
		case protoreflect.BytesKind:
			g.P("        if (bp_read_bits(", rv, ", ", fo.lengthBits, ", &_v)) return -1;")
			g.P("        msg->", oneofName, ".", fname, ".len = (uint16_t)_v;")
			g.P("        if (bp_read_raw_bytes(", rv, ", msg->", oneofName, ".", fname, ".len, msg->", oneofName, ".", fname, ".data)) return -1;")
		default:
			if err := emitDecodeScalarValue(g, fd, fo, fmt.Sprintf("msg->%s.%s", oneofName, fname), "        ", rv); err != nil {
				return err
			}
		}
		g.P("        break;")
	}

	g.P("    default: return -1;")
	g.P("    }")
	return nil
}

// ── Encode ────────────────────────────────────────────────────────────────────

func emitEncodeUnit(g *protogen.GeneratedFile, u unit, msg *protogen.Message, wv string) error {
	switch u := u.(type) {
	case scalarUnit:
		return emitEncodeScalar(g, u, msg, wv)
	case oneofUnit:
		return emitEncodeOneof(g, u, msg, wv)
	}
	return nil
}

func emitEncodeScalar(g *protogen.GeneratedFile, u scalarUnit, msg *protogen.Message, wv string) error {
	fd := u.fd
	fo := u.fo
	name := string(fd.Name())

	if fd.IsMap() {
		g.P("    /* map field '", name, "' skipped */")
		return nil
	}

	if u.isOptional {
		g.P("    /* optional ", name, " */")
		g.P("    if (bp_write_bits(", wv, ", msg->has_", name, " ? 1u : 0u, 1)) return -1;")
		g.P("    if (msg->has_", name, ") {")
		if err := emitEncodeScalarValue(g, fd, fo, "msg->"+name, "        ", wv); err != nil {
			return err
		}
		g.P("    }")
		return nil
	}

	if u.isTimestamp {
		bits := fo.bits
		if bits == 0 {
			bits = 64
		}
		g.P("    /* timestamp ", name, " */")
		g.P("    if (bp_write_bits(", wv, ", msg->has_", name, " ? 1u : 0u, 1)) return -1;")
		g.P("    if (msg->has_", name, ") {")
		g.P("        if (bp_write_bits(", wv, ", (uint64_t)msg->", name, ", ", bits, ")) return -1;")
		g.P("    }")
		return nil
	}

	if u.isMessage {
		nestedName := cMsgTypeName(fd.Message())
		g.P("    /* message ", name, " */")
		g.P("    if (bp_write_bits(", wv, ", msg->has_", name, " ? 1u : 0u, 1)) return -1;")
		if !isEmptyMsg(fd.Message()) {
			g.P("    if (msg->has_", name, ") {")
			g.P("        if (bp_encode_", nestedName, "_w(&msg->", name, ", ", wv, ") != 0) return -1;")
			g.P("    }")
		}
		return nil
	}

	if fd.IsList() {
		return emitEncodeList(g, fd, fo, name, wv)
	}

	return emitEncodeScalarValue(g, fd, fo, "msg->"+name, "    ", wv)
}

func emitEncodeList(g *protogen.GeneratedFile, fd protoreflect.FieldDescriptor, fo bpOpts, name, wv string) error {
	g.P("    /* repeated ", name, " */")
	g.P("    if (bp_write_bits(", wv, ", (uint64_t)msg->", name, "_count, ", fo.countBits, ")) return -1;")
	g.P("    for (uint16_t _i = 0; _i < msg->", name, "_count; _i++) {")

	switch fd.Kind() {
	case protoreflect.MessageKind:
		if !isEmptyMsg(fd.Message()) {
			nestedName := cMsgTypeName(fd.Message())
			g.P("        if (bp_encode_", nestedName, "_w(&msg->", name, "[_i], ", wv, ") != 0) return -1;")
		}
	case protoreflect.StringKind:
		g.P("        if (bp_write_bits(", wv, ", (uint64_t)msg->", name, "_lens[_i], ", fo.lengthBits, ")) return -1;")
		g.P("        if (bp_write_raw_bytes(", wv, ", (const uint8_t*)msg->", name, "[_i], msg->", name, "_lens[_i])) return -1;")
	case protoreflect.BytesKind:
		g.P("        if (bp_write_bits(", wv, ", (uint64_t)msg->", name, "_lens[_i], ", fo.lengthBits, ")) return -1;")
		g.P("        if (bp_write_raw_bytes(", wv, ", msg->", name, "[_i], msg->", name, "_lens[_i])) return -1;")
	default:
		if err := emitEncodeScalarValue(g, fd, fo, fmt.Sprintf("msg->%s[_i]", name), "        ", wv); err != nil {
			return err
		}
	}

	g.P("    }")
	return nil
}

func emitEncodeScalarValue(g *protogen.GeneratedFile, fd protoreflect.FieldDescriptor, fo bpOpts, src, indent, wv string) error {
	switch fd.Kind() {
	case protoreflect.BoolKind:
		g.P(indent, "if (bp_write_bits(", wv, ", ", src, " ? 1u : 0u, 1)) return -1;")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P(indent, "if (bp_write_bits(", wv, ", (uint64_t)(", src, "), ", fo.bits, ")) return -1;")
	case protoreflect.Int32Kind, protoreflect.Sfixed32Kind:
		g.P(indent, "if (bp_write_bits(", wv, ", (uint64_t)(uint32_t)(", src, "), ", fo.bits, ")) return -1;")
	case protoreflect.Sint32Kind:
		g.P(indent, "if (bp_write_bits(", wv, ", (uint64_t)bp_zigzag32(", src, "), ", fo.bits, ")) return -1;")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P(indent, "if (bp_write_bits(", wv, ", (", src, "), ", fo.bits, ")) return -1;")
	case protoreflect.Int64Kind, protoreflect.Sfixed64Kind:
		g.P(indent, "if (bp_write_bits(", wv, ", (uint64_t)(", src, "), ", fo.bits, ")) return -1;")
	case protoreflect.Sint64Kind:
		g.P(indent, "if (bp_write_bits(", wv, ", bp_zigzag64(", src, "), ", fo.bits, ")) return -1;")
	case protoreflect.FloatKind:
		return emitEncodeFloat(g, fo, src, indent, wv)
	case protoreflect.DoubleKind:
		return emitEncodeDouble(g, fo, src, indent, wv)
	case protoreflect.StringKind:
		lenSrc := src + "_len"
		g.P(indent, "if (bp_write_bits(", wv, ", (uint64_t)", lenSrc, ", ", fo.lengthBits, ")) return -1;")
		g.P(indent, "if (bp_write_raw_bytes(", wv, ", (const uint8_t*)", src, ", ", lenSrc, ")) return -1;")
	case protoreflect.BytesKind:
		lenSrc := src + "_len"
		g.P(indent, "if (bp_write_bits(", wv, ", (uint64_t)", lenSrc, ", ", fo.lengthBits, ")) return -1;")
		g.P(indent, "if (bp_write_raw_bytes(", wv, ", ", src, ", ", lenSrc, ")) return -1;")
	case protoreflect.EnumKind:
		g.P(indent, "if (bp_write_bits(", wv, ", (uint64_t)(", src, "), ", fo.bits, ")) return -1;")
	}
	return nil
}

func emitEncodeFloat(g *protogen.GeneratedFile, fo bpOpts, src, indent, wv string) error {
	if fo.isFixed {
		if fo.isSigned {
			g.P(indent, "if (bp_write_bits(", wv, ", (uint64_t)bp_float_to_fixed(", src, ", ", fo.decimalPlaces, "), ", fo.bits, ")) return -1;")
		} else {
			g.P(indent, "if (bp_write_bits(", wv, ", bp_float_to_ufixed(", src, ", ", fo.decimalPlaces, "), ", fo.bits, ")) return -1;")
		}
		return nil
	}
	bits := fo.bits
	if bits == 0 {
		bits = 32
	}
	switch bits {
	case 16:
		g.P(indent, "if (bp_write_bits(", wv, ", (uint64_t)bp_f32_to_f16(", src, "), 16)) return -1;")
	default:
		g.P(indent, "{ uint32_t _b32; memcpy(&_b32, &(", src, "), 4); if (bp_write_bits(", wv, ", (uint64_t)_b32, 32)) return -1; }")
	}
	return nil
}

func emitEncodeDouble(g *protogen.GeneratedFile, fo bpOpts, src, indent, wv string) error {
	if fo.isFixed {
		if fo.isSigned {
			g.P(indent, "if (bp_write_bits(", wv, ", (uint64_t)bp_double_to_fixed(", src, ", ", fo.decimalPlaces, "), ", fo.bits, ")) return -1;")
		} else {
			g.P(indent, "if (bp_write_bits(", wv, ", bp_double_to_ufixed(", src, ", ", fo.decimalPlaces, "), ", fo.bits, ")) return -1;")
		}
		return nil
	}
	bits := fo.bits
	if bits == 0 {
		bits = 64
	}
	switch bits {
	case 16:
		g.P(indent, "if (bp_write_bits(", wv, ", (uint64_t)bp_f32_to_f16((float)(", src, ")), 16)) return -1;")
	case 32:
		g.P(indent, "{ float _f32 = (float)(", src, "); uint32_t _b32; memcpy(&_b32, &_f32, 4); if (bp_write_bits(", wv, ", (uint64_t)_b32, 32)) return -1; }")
	default:
		g.P(indent, "{ uint64_t _b64; memcpy(&_b64, &(", src, "), 8); if (bp_write_bits(", wv, ", _b64, 64)) return -1; }")
	}
	return nil
}

func emitEncodeOneof(g *protogen.GeneratedFile, u oneofUnit, msg *protogen.Message, wv string) error {
	msgName := string(msg.Desc.Name())
	oneofName := string(u.od.Name())
	noneName := cOneofNoneEnumerant(msgName, oneofName)

	g.P("    /* oneof ", oneofName, " */")
	g.P("    if (bp_write_bits(", wv, ", (uint64_t)msg->which_", oneofName, ", ", u.selectorBits, ")) return -1;")
	g.P("    switch (msg->which_", oneofName, ") {")
	g.P("    case ", noneName, ": break;")

	for i, field := range u.fields {
		fd := field.fd
		fo := field.fo
		fname := string(fd.Name())
		enumerant := cOneofEnumerantName(msgName, oneofName, fname)
		g.P("    case ", enumerant, ": /* selector=", i+1, " */")
		switch fd.Kind() {
		case protoreflect.MessageKind:
			if !isEmptyMsg(fd.Message()) {
				nestedName := cMsgTypeName(fd.Message())
				g.P("        if (bp_encode_", nestedName, "_w(&msg->", oneofName, ".", fname, ", ", wv, ") != 0) return -1;")
			}
		case protoreflect.StringKind:
			g.P("        if (bp_write_bits(", wv, ", (uint64_t)msg->", oneofName, ".", fname, ".len, ", fo.lengthBits, ")) return -1;")
			g.P("        if (bp_write_raw_bytes(", wv, ", (const uint8_t*)msg->", oneofName, ".", fname, ".data, msg->", oneofName, ".", fname, ".len)) return -1;")
		case protoreflect.BytesKind:
			g.P("        if (bp_write_bits(", wv, ", (uint64_t)msg->", oneofName, ".", fname, ".len, ", fo.lengthBits, ")) return -1;")
			g.P("        if (bp_write_raw_bytes(", wv, ", msg->", oneofName, ".", fname, ".data, msg->", oneofName, ".", fname, ".len)) return -1;")
		default:
			if err := emitEncodeScalarValue(g, fd, fo, fmt.Sprintf("msg->%s.%s", oneofName, fname), "        ", wv); err != nil {
				return err
			}
		}
		g.P("        break;")
	}

	g.P("    default: break;")
	g.P("    }")
	return nil
}
