package main

// runtimeHeader is the content of bitpacker_runtime.h, emitted once per buf generate run.
const runtimeHeader = `#pragma once
/* bitpacker_runtime.h — generated by protoc-gen-bitpacker-c, do not edit */
/* Pure C99, header-only, all functions static inline — zero overhead on ESP32. */

#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

/* ── Bit-stream types ─────────────────────────────────────────────────────── */

typedef struct {
    const uint8_t *buf;
    uint32_t       bit_pos;
    uint32_t       bit_len; /* total bits available */
} bp_reader_t;

typedef struct {
    uint8_t  *buf;
    uint32_t  bit_pos;
    uint32_t  bit_cap; /* capacity in bits */
} bp_writer_t;

/* ── Reader ───────────────────────────────────────────────────────────────── */

/* Read n bits (1–64) into *out, MSB first. Returns 0 on success, -1 on EOF. */
static inline int bp_read_bits(bp_reader_t *r, int n, uint64_t *out) {
    if ((uint32_t)n > r->bit_len - r->bit_pos) return -1;
    uint64_t val = 0;
    for (int i = 0; i < n; i++) {
        uint32_t byte_idx = r->bit_pos >> 3;
        uint32_t bit_idx  = 7u - (r->bit_pos & 7u);
        val = (val << 1) | ((r->buf[byte_idx] >> bit_idx) & 1u);
        r->bit_pos++;
    }
    *out = val;
    return 0;
}

/* Read n_bytes raw bytes into out, MSB-first within each byte. Returns 0 or -1. */
static inline int bp_read_raw_bytes(bp_reader_t *r, uint32_t n_bytes, uint8_t *out) {
    for (uint32_t i = 0; i < n_bytes; i++) {
        uint64_t v;
        if (bp_read_bits(r, 8, &v) != 0) return -1;
        out[i] = (uint8_t)v;
    }
    return 0;
}

/* ── Writer ───────────────────────────────────────────────────────────────── */

/* Write low n bits of val, MSB first. Returns 0 on success, -1 on overflow. */
static inline int bp_write_bits(bp_writer_t *w, uint64_t val, int n) {
    if (w->bit_pos + (uint32_t)n > w->bit_cap) return -1;
    for (int i = n - 1; i >= 0; i--) {
        uint32_t byte_idx = w->bit_pos >> 3;
        uint32_t bit_idx  = 7u - (w->bit_pos & 7u);
        if ((val >> (unsigned)i) & 1u)
            w->buf[byte_idx] |= (uint8_t)(1u << bit_idx);
        else
            w->buf[byte_idx] &= (uint8_t)~(1u << bit_idx);
        w->bit_pos++;
    }
    return 0;
}

/* Write n_bytes raw bytes, MSB-first within each byte. Returns 0 or -1. */
static inline int bp_write_raw_bytes(bp_writer_t *w, const uint8_t *data, uint32_t n_bytes) {
    for (uint32_t i = 0; i < n_bytes; i++) {
        if (bp_write_bits(w, (uint64_t)data[i], 8) != 0) return -1;
    }
    return 0;
}

/* ── Zigzag encode / decode ───────────────────────────────────────────────── */

static inline uint32_t bp_zigzag32(int32_t v)  { return (uint32_t)((v << 1) ^ (v >> 31)); }
static inline uint64_t bp_zigzag64(int64_t v)  { return (uint64_t)((v << 1) ^ (v >> 63)); }
static inline int32_t  bp_zagzig32(uint32_t v) { return (int32_t)((v >> 1) ^ -(v & 1u)); }
static inline int64_t  bp_zagzig64(uint64_t v) { return (int64_t)((v >> 1) ^ -(v & 1ull)); }

/* ── Sign extension ───────────────────────────────────────────────────────── */

/* Sign-extend a value that was read with fewer than 32 bits. */
static inline int32_t bp_sign_ext32(uint64_t v, int bits) {
    if (bits >= 32) return (int32_t)v;
    if (v >> (unsigned)(bits - 1)) v |= ~((uint64_t)((1u << (unsigned)bits) - 1u));
    return (int32_t)v;
}

/* Sign-extend a value that was read with fewer than 64 bits. */
static inline int64_t bp_sign_ext64(uint64_t v, int bits) {
    if (bits >= 64) return (int64_t)v;
    if (v >> (unsigned)(bits - 1)) v |= ~((UINT64_C(1) << (unsigned)bits) - 1u);
    return (int64_t)v;
}

/* ── IEEE 754 float16 ↔ float32 ──────────────────────────────────────────── */

static inline float bp_f16_to_f32(uint16_t h) {
    uint32_t sign  = (uint32_t)(h >> 15) << 31;
    int      exp   = (h >> 10) & 0x1F;
    uint32_t mant  = h & 0x3FFu;
    if (exp == 31) { /* NaN / Inf */
        uint32_t bits = sign | 0x7F800000u | mant;
        float f; memcpy(&f, &bits, 4); return f;
    }
    if (exp == 0) { /* subnormal */
        if (mant == 0) { float f; uint32_t b = sign; memcpy(&f, &b, 4); return f; }
        exp = 1;
        while (!(mant & 0x400u)) { mant <<= 1; exp--; }
        mant &= ~0x400u;
    }
    exp += 127 - 15;
    { uint32_t bits = sign | ((uint32_t)exp << 23) | (mant << 13);
      float f; memcpy(&f, &bits, 4); return f; }
}

static inline uint16_t bp_f32_to_f16(float f) {
    uint32_t bits; memcpy(&bits, &f, 4);
    uint16_t sign = (uint16_t)((bits >> 31) & 0x1u);
    int      exp  = (int)((bits >> 23) & 0xFFu);
    uint32_t mant = bits & 0x7FFFFFu;
    if (exp == 0xFF) return mant ? (uint16_t)(sign << 15 | 0x7C01u) : (uint16_t)(sign << 15 | 0x7C00u);
    exp = exp - 127 + 15;
    if (exp >= 31) return (uint16_t)(sign << 15 | 0x7C00u);
    if (exp <= 0) {
        if (exp < -10) return (uint16_t)(sign << 15);
        mant = (mant | 0x800000u) >> (unsigned)(1 - exp);
        return (uint16_t)(sign << 15 | (uint16_t)(mant >> 13));
    }
    return (uint16_t)(sign << 15 | (uint16_t)exp << 10 | (uint16_t)(mant >> 13));
}

/* ── Fixed-point float helpers ────────────────────────────────────────────── */

/* Convert signed fixed-point integer (decimal_places decimal digits) → float */
static inline float bp_fixed_to_float(int64_t raw, uint32_t decimal_places) {
    double div = 1.0;
    for (uint32_t i = 0; i < decimal_places; i++) div *= 10.0;
    return (float)((double)raw / div);
}

/* Convert unsigned fixed-point integer → float */
static inline float bp_ufixed_to_float(uint64_t raw, uint32_t decimal_places) {
    double div = 1.0;
    for (uint32_t i = 0; i < decimal_places; i++) div *= 10.0;
    return (float)((double)raw / div);
}

/* Convert float → signed fixed-point integer */
static inline int64_t bp_float_to_fixed(float f, uint32_t decimal_places) {
    double mul = 1.0;
    for (uint32_t i = 0; i < decimal_places; i++) mul *= 10.0;
    return (int64_t)round((double)f * mul);
}

/* Convert float → unsigned fixed-point integer */
static inline uint64_t bp_float_to_ufixed(float f, uint32_t decimal_places) {
    double mul = 1.0;
    for (uint32_t i = 0; i < decimal_places; i++) mul *= 10.0;
    return (uint64_t)round((double)f * mul);
}

/* Convert signed fixed-point integer → double */
static inline double bp_fixed_to_double(int64_t raw, uint32_t decimal_places) {
    double div = 1.0;
    for (uint32_t i = 0; i < decimal_places; i++) div *= 10.0;
    return (double)raw / div;
}

/* Convert unsigned fixed-point integer → double */
static inline double bp_ufixed_to_double(uint64_t raw, uint32_t decimal_places) {
    double div = 1.0;
    for (uint32_t i = 0; i < decimal_places; i++) div *= 10.0;
    return (double)raw / div;
}

/* Convert double → signed fixed-point integer (rounds to nearest, like the Go encoder) */
static inline int64_t bp_double_to_fixed(double d, uint32_t decimal_places) {
    double mul = 1.0;
    for (uint32_t i = 0; i < decimal_places; i++) mul *= 10.0;
    return (int64_t)round(d * mul);
}

/* Convert double → unsigned fixed-point integer (rounds to nearest, like the Go encoder) */
static inline uint64_t bp_double_to_ufixed(double d, uint32_t decimal_places) {
    double mul = 1.0;
    for (uint32_t i = 0; i < decimal_places; i++) mul *= 10.0;
    return (uint64_t)round(d * mul);
}

/* ── Writer: bytes written so far ─────────────────────────────────────────── */

/* Returns the number of bytes used in the output buffer (rounded up). */
static inline uint32_t bp_writer_bytes(const bp_writer_t *w) {
    return (w->bit_pos + 7u) / 8u;
}

/* Zero the padding bits of the last partial byte (the buffer may hold stale data)
 * and return the number of bytes written. */
static inline uint32_t bp_writer_finish(bp_writer_t *w) {
    uint32_t used = w->bit_pos & 7u;
    if (used) w->buf[w->bit_pos >> 3] &= (uint8_t)(0xFFu << (8u - used));
    return bp_writer_bytes(w);
}
`
